spring:
  profiles:
    active: com
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      max-active: 200
      max-idle: 200
      min-idle: 10
      test-on-borrow: true
      test-on-return: true
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1
      idle-timeout: 120000
      connection-timeout: 6000
      maxIdleTime: 60
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8079